import {applyGenome,createWorld,decodeGenome,encodeGenome,hashSeed,step} from './simulation.mjs';
const $=id=>document.getElementById(id), canvas=$('world'),ctx=canvas.getContext('2d'),portrait=$('portrait').getContext('2d');
let world,input={x:0,y:0,target:null,boost:false},paused=false,last=performance.now(),lastEvent=0,toastTimer;
const stages=[['ЗАРОЖДЕНИЕ','01'],['АДАПТАЦИЯ','02'],['СООБЩЕСТВО','03'],['РАЗУМ','04']];
function log(title,text=''){const li=document.createElement('li');li.innerHTML=`<b>${title}</b>${text}`;$('log').prepend(li);while($('log').children.length>6)$('log').lastChild.remove()}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function reset(seed){world=createWorld(seed,canvas.width,canvas.height);input.target=null;$('seed-label').textContent=hashSeed(seed).toString(16).toUpperCase().padStart(8,'0');$('log').innerHTML='';log('МИР ПРОБУДИЛСЯ',`Seed ${seed}`);toast('Новая жизнь начинается');}
function drawCreature(c,g,context=ctx,scale=1){context.save();context.translate(c.x,c.y);context.rotate(c.angle||0);context.shadowColor='#c9ed62';context.shadowBlur=12*scale;context.fillStyle='#c9ed62';context.beginPath();context.ellipse(0,0,(7+g.armor*1.3)*scale,(5+g.armor*.5)*scale,0,0,Math.PI*2);context.fill();context.fillStyle='#173c34';for(let i=0;i<g.sense;i++){context.beginPath();context.arc((5+i*.8)*scale,(-3+i*1.5)*scale,1.2*scale,0,7);context.fill()}context.strokeStyle='#8cbf57';context.lineWidth=1.5*scale;for(const side of [-1,1]){context.beginPath();context.moveTo(-2*scale,side*4*scale);context.quadraticCurveTo(-8*scale,side*9*scale,-12*scale,side*8*scale);context.stroke()}context.restore()}
function draw(){const w=canvas.width,h=canvas.height;let grad=ctx.createRadialGradient(w*.5,h*.45,20,w*.5,h*.45,w*.75);grad.addColorStop(0,'#174c40');grad.addColorStop(1,'#071d1c');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);
  ctx.lineWidth=1;for(let x=-40;x<w;x+=48)for(let y=-40;y<h;y+=42){ctx.strokeStyle=`rgba(94,160,128,${.035+((x+y)%3)*.01})`;ctx.beginPath();ctx.arc(x+(y%84?24:0),y,28,0,7);ctx.stroke()}
  for(const m of world.motes){ctx.fillStyle=`rgba(183,233,154,${m.a})`;ctx.beginPath();ctx.arc(m.x,m.y,m.r,0,7);ctx.fill()}
  for(const h of world.hazards){const hg=ctx.createRadialGradient(h.x,h.y,0,h.x,h.y,h.r);hg.addColorStop(0,'#8e403055');hg.addColorStop(1,'#251c1900');ctx.fillStyle=hg;ctx.beginPath();ctx.arc(h.x,h.y,h.r,0,7);ctx.fill()}
  for(const f of world.food){const near=Math.hypot(f.x-world.creatures[0].x,f.y-world.creatures[0].y)<world.genome.sense*48;ctx.fillStyle=near?'#d8ff6a':'#68a778';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=near?10:2;ctx.beginPath();ctx.arc(f.x,f.y,f.size,0,7);ctx.fill()}ctx.shadowBlur=0;
  world.creatures.slice(1).forEach(c=>drawCreature(c,world.genome));drawCreature(world.creatures[0],world.genome,ctx,1.35);
  if(input.target){ctx.strokeStyle='#c9ed6288';ctx.beginPath();ctx.arc(input.target.x,input.target.y,10+Math.sin(world.time*5)*3,0,7);ctx.stroke()}
  drawPortrait();
}
function drawPortrait(){portrait.clearRect(0,0,240,150);const g=portrait.createRadialGradient(120,75,2,120,75,100);g.addColorStop(0,'#286151');g.addColorStop(1,'#0b2623');portrait.fillStyle=g;portrait.fillRect(0,0,240,150);drawCreature({x:120,y:72,angle:-.12},world.genome,portrait,4)}
function updateUI(){const p=world.creatures[0],level=Math.min(3,Math.floor(world.dna/4));$('energy').value=p.energy;$('energy-label').textContent=`${Math.round(p.energy)} / 100`;$('dna').value=world.dna%4;$('dna-label').textContent=`${world.dna%4} / 4`;$('generation').textContent=world.generation;$('population').textContent=world.creatures.length;$('food-count').textContent=world.food.length;$('age').textContent=`${Math.floor(world.time/60)}:${String(Math.floor(world.time%60)).padStart(2,'0')}`;$('fitness').textContent=Math.round((p.energy+world.creatures.length*12)/2);$('goal-state').textContent=`${Math.min(world.creatures.length,2)} / 2 существа`;$('mutate').disabled=p.energy<25;$('stage-name').textContent=stages[level][0];$('stage-number').textContent=stages[level][1];}
function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(!paused){step(world,input,dt);if(world.events.length>lastEvent){const event=world.events.at(-1);log(event,event.includes('новое')?'Популяция растёт':'Энергия восстановлена');toast(event);lastEvent=world.events.length}updateUI()}draw();requestAnimationFrame(frame)}
for(const id of ['speed','sense','armor'])$(id).addEventListener('input',e=>{$(`${id}-value`).textContent=e.target.value});
$('mutate').onclick=()=>{const genome=Object.fromEntries(['speed','sense','armor'].map(k=>[k,Number($(k).value)]));if(applyGenome(world,genome)){log('МУТАЦИЯ ЗАКРЕПЛЕНА',`Поколение ${world.generation}`);toast('Геном изменён')}};
$('share').onclick=async()=>{const code=encodeGenome(world.genome);try{await navigator.clipboard.writeText(code);toast('Геном скопирован')}catch{prompt('Код генома',code)}};
$('new-world').onclick=()=>reset($('seed').value.trim()||`CORORO-${Date.now()}`);$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶':'Ⅱ';toast(paused?'Симуляция остановлена':'Жизнь продолжается')};
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key==='w'||e.key==='ArrowUp')input.y=-1;if(e.key==='s'||e.key==='ArrowDown')input.y=1;if(e.key==='a'||e.key==='ArrowLeft')input.x=-1;if(e.key==='d'||e.key==='ArrowRight')input.x=1;if(e.code==='Space')input.boost=true});
addEventListener('keyup',e=>{if(['w','s','ArrowUp','ArrowDown'].includes(e.key))input.y=0;if(['a','d','ArrowLeft','ArrowRight'].includes(e.key))input.x=0;if(e.code==='Space')input.boost=false});canvas.onclick=e=>{const r=canvas.getBoundingClientRect();input.target={x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};
const shared=new URLSearchParams(location.search).get('genome');reset('CORORO-42');if(shared)try{world.genome=decodeGenome(shared)}catch{toast('Код генома повреждён')}requestAnimationFrame(frame);
